services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mydb
      MYSQL_DATABASE: mydb
    ports:
      - 3307:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local