services:
  db-service:
    image: mysql:latest
    container_name: db-service-container
    environment:
      MYSQL_ROOT_PASSWORD: mydb
      MYSQL_DATABASE: mydb
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$(echo $MYSQL_ROOT_PASSWORD) --silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  cliente-service:
    image: davidgaleno/api-restful-mvc:v1
    container_name: cliente-service-container
    environment:
      - QUARKUS_CLIENT_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=mydb
      - QUARKUS_DATASOURCE_HOST=db-service
      - QUARKUS_DATASOURCE_PORT=3306
    ports:
      - 8080:8080
    depends_on:
      db-service:
        condition: service_healthy
volumes:
  mysql_data:
    driver: local